### ISSUE TITLE
make normalization features selectable?

### ISSUE THREAD

**Issue by brobertson** [jtauber/greek-normalisation#1]
Would you consider adding to the api the ability to select certain normalization features and not select others? In particular, some OCR texts use capitalization more liberally than your process expects, and I would want to turn this normalization feature off.

**Comment by jtauber** [comment]
Absolutely. In fact, I'm working on a whole series of regular expressions at the moment that catch different levels of error and according to different editorial conventions.

 If it's easier, we can hash out specific needs in Slack or on a call some time.

**Comment by brobertson** [comment]
I propose a 40 min. conversation on Thursday morning, driving everyone else off the conference call!

**Comment by jtauber** [comment]
The 0.5 release has the ability to set which of the various normalisations you want to do (in any combination).
